definitions:
  models.GroupBasic:
    properties:
      createdAt:
        type: string
      icon:
        items:
          type: integer
        type: array
      id:
        type: integer
      members:
        items:
          $ref: '#/definitions/models.UserBasic'
        type: array
      name:
        type: string
      ownerId:
        type: string
      type:
        type: integer
      updatedAt:
        type: string
    type: object
  models.Message:
    properties:
      content: {}
      contentType:
        type: integer
      createdAt:
        type: string
      msgType:
        type: integer
      receiverId:
        type: string
      senderId:
        type: string
    type: object
  models.UserBasic:
    properties:
      birthday:
        type: string
      createdAt:
        type: string
      email:
        type: string
      groups:
        items:
          $ref: '#/definitions/models.GroupBasic'
        type: array
      homeAddress:
        type: string
      icon:
        items:
          type: integer
        type: array
      id:
        type: string
      ipAddress:
        type: string
      loginTime:
        type: string
      password:
        type: string
      phone:
        type: string
      updatedAt:
        type: string
      userName:
        type: string
    type: object
  server.RespJson:
    properties:
      code:
        type: integer
      count:
        type: integer
      data: {}
      msg: {}
    type: object
info:
  contact: {}
paths:
  /friend/agree:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 被同意的用户id
        in: formData
        name: agreedId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 同意好友请求
      tags:
      - 好友
  /friend/delete:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 被删除的用户id
        in: formData
        name: deletedId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 删除好友
      tags:
      - 好友
  /friend/getList:
    get:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 获取好友列表
      tags:
      - 好友
  /friend/request:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 被请求的用户id
        in: formData
        name: requestedId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 发送好友请求
      tags:
      - 好友
  /group/create:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - collectionFormat: csv
        description: 初始群员id,应包括群主
        in: formData
        items:
          type: string
        name: members
        required: true
        type: array
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 创建群组
      tags:
      - 群
  /group/delete:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 群id
        in: formData
        name: groupId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 删除群聊
      tags:
      - 群
  /group/enterAgree:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 群id
        in: formData
        name: groupId
        required: true
        type: string
      - description: 被同意id
        in: formData
        name: agreedId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 同意群申请
      tags:
      - 群
  /group/enterReq:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 群id
        in: formData
        name: groupId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 发送加群申请
      tags:
      - 群
  /group/getGroup:
    get:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 群id
        in: formData
        name: groupId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 获取群信息
      tags:
      - 群
  /group/getMembers:
    get:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 群id
        in: formData
        name: groupId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 获取群员信息
      tags:
      - 群
  /group/inviteMember:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 群id
        in: formData
        name: groupId
        required: true
        type: string
      - collectionFormat: csv
        description: 被邀请用户id
        in: formData
        items:
          type: string
        name: invitedMembers
        required: true
        type: array
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 邀请入群
      tags:
      - 群
  /group/removeMember:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 群id
        in: formData
        name: groupId
        required: true
        type: string
      - description: 被删除用户id
        in: formData
        name: deletedId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 删除群员
      tags:
      - 群
  /message/getPush:
    get:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 创建通知通道
      tags:
      - 消息操作
  /tool/getMessageJson:
    post:
      parameters:
      - description: 消息
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.Message'
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 获取消息json格式
      tags:
      - 工具
  /user/create:
    post:
      parameters:
      - description: 用户手机
        in: formData
        name: phone
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 用户名
        in: formData
        name: userName
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 创建用户
      tags:
      - 用户操作
  /user/delete:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 删除用户
      tags:
      - 用户操作
  /user/find:
    get:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 被查询用户Id
        in: query
        name: queriedId
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 获取用户
      tags:
      - 用户操作
  /user/login:
    post:
      parameters:
      - description: 用户id
        in: formData
        name: id
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 用户登录
      tags:
      - 用户操作
  /user/update:
    post:
      parameters:
      - description: 用户令牌
        in: header
        name: Authenticate
        required: true
        type: string
      - description: 用户json信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserBasic'
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/server.RespJson'
        "400":
          description: 参数有误
          schema:
            $ref: '#/definitions/server.RespJson'
        "401":
          description: 验证失败
          schema:
            $ref: '#/definitions/server.RespJson'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/server.RespJson'
      summary: 更新用户
      tags:
      - 用户操作
swagger: "2.0"
